name: CI

on:
  push:
    branches: [ main, master, develop, dev, feature/** ]
  pull_request:
    branches: [ main, master, develop, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install (workspaces)
        run: |
          npm install
          npm run install:workspaces

      - name: Build shared ao-client
        run: npm -w packages/ao-client run build

      - name: Build shared ao-client only
        run: echo "ao-client built; skipping app builds for this PR"
